[build-system]
build-backend = "cmeel"
requires = [
  "cmeel[build]",
  "example-robot-data[build]"
]

[project]
dependencies = [
  "example-robot-data"
]
description = "Data specific to ur5 and 10 robots for hpp-corbaserver"
license = "BSD-2-Clause"
name = "hpp-universal-robot"
requires-python = ">= 3.10"
version = "9.0.2"

[project.urls]
homepage = "https://github.com/cmake-wheel/hpp-universal-robot"
repository = "https://github.com/cmake-wheel/hpp-universal-robot.git"
upstream = "https://github.com/humanoid-path-planner/hpp-universal-robot"

[tool.cmeel]
has-binaries = false

[tool.ruff.lint]
extend-select = ["I", "NPY", "RUF", "UP", "W"]

[tool.tomlsort]
all = true
